import type { NormalizedRule } from './types.js';

export const MANAGED_START = '<!-- rulebridge:start -->';
export const MANAGED_END = '<!-- rulebridge:end -->';
export const GENERATED_MARKER = '<!-- Generated by RuleBridge. Safe to replace. -->';

function uniqueRules(rules: NormalizedRule[]) {
  const seen = new Set<string>();
  return rules.filter((rule) => {
    const key = `${rule.content.trim()}\0${(rule.scope?.globs ?? []).join(',')}\0${rule.alwaysApply}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function renderMergedBody(rules: NormalizedRule[]) {
  const deduped = uniqueRules(rules);
  return deduped
    .map((rule) => {
      const scope = rule.alwaysApply || !rule.scope?.globs.length
        ? 'all files'
        : rule.scope.globs.join(', ');
      return `### From ${rule.sourceAgent}: ${rule.sourcePath}\nScope: ${scope}\n\n${rule.content.trim()}`;
    })
    .join('\n\n');
}

export function renderManagedMarkdown(existing: string | undefined, rules: NormalizedRule[]) {
  const block = `${MANAGED_START}\n## RuleBridge managed rules\n\n${renderMergedBody(rules)}\n${MANAGED_END}`;
  if (!existing?.trim()) return `${block}\n`;

  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start !== -1 && end !== -1 && end >= start) {
    const before = existing.slice(0, start).trimEnd();
    const after = existing.slice(end + MANAGED_END.length).trimStart();
    return `${before}${before ? '\n\n' : ''}${block}${after ? `\n\n${after}` : '\n'}`;
  }

  return `${existing.trimEnd()}\n\n${block}\n`;
}

function quote(value: string) {
  return JSON.stringify(value);
}

export function renderCursorRule(rule: NormalizedRule) {
  const frontmatter: string[] = ['---'];
  if (rule.description) frontmatter.push(`description: ${quote(rule.description)}`);
  if (rule.scope?.globs.length) frontmatter.push(`globs: [${rule.scope.globs.map(quote).join(', ')}]`);
  frontmatter.push(`alwaysApply: ${rule.alwaysApply ? 'true' : 'false'}`);
  frontmatter.push('---');
  return `${GENERATED_MARKER}\n${frontmatter.join('\n')}\n\n${rule.content.trim()}\n`;
}

export function renderCopilotRule(rule: NormalizedRule) {
  const frontmatter: string[] = ['---'];
  if (rule.description) frontmatter.push(`description: ${quote(rule.description)}`);
  if (rule.scope?.globs.length) frontmatter.push(`applyTo: ${quote(rule.scope.globs.join(','))}`);
  frontmatter.push('---');
  return `${GENERATED_MARKER}\n${frontmatter.join('\n')}\n\n${rule.content.trim()}\n`;
}

export function isRuleBridgeGenerated(content: string) {
  return content.includes(GENERATED_MARKER) || content.includes(MANAGED_START);
}
